version: "3.8"
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=C0V1D19
      - POSTGRES_DB=scrape_youtube_db
    ports:
      - "54320:5432"
    volumes:
      - ./server/data:/var/lib/postgresql/data/

  server:
    container_name: syv-server
    build:
      context: server
      dockerfile: Dockerfile
    command: ["python", "server/manage.py", "runserver", "0.0.0.0:8080"]
#    command: ["./wait-for-it.sh", "db:5432", "--", "python", "server/manage.py", "runserver", "0.0.0.0:8080"]
    ports:
      - "8000:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: on-failure

  client:
    container_name: syv-client
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    restart: on-failure