version: "3.8"
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=C0V1D19
      - POSTGRES_DB=scrape_youtube_db
    ports:
      - "54320:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/

  backend:
    container_name: syv-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    ports:
      - "8000:8080"
    volumes:
      - .:/app
    depends_on:
      - db
