# Generated by Django 3.2.12 on 2022-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('view_count', models.PositiveBigIntegerField()),
                ('subscriber_count', models.PositiveBigIntegerField()),
                ('video_count', models.PositiveBigIntegerField()),
                ('published_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'channel',
            },
        ),
    ]
