# Generated by Django 3.2.12 on 2022-08-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_tag_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
    ]
